add eslint
PraiseTy/Short-It pull request #2
Opened 2023-10-07 18:32 UTC by PraiseTy

2023-10-07 19:04 UTC, greatertomi requested changes

2023-10-07 19:04 UTC, greatertomi commented on .env
Remove this.

2023-10-08 22:50 UTC, PraiseTy commented on .env
done. Also since you said the mongo uri is a secret variable and I shouldn't expose it, does that mean I don't have to create the env.example file?

2023-10-09 09:12 UTC, greatertomi approved these changes

2023-10-09 09:13 UTC, greatertomi commented on .env
You can create .env.example in #1  and just add `MONGO_URI=` without the connection string.

2023-10-09 18:39 UTC, merged